semestrul4/pweb/simulari/genericproject/adaugasterge/urls.py
from django.urls import path

from adaugasterge import views
from testapp.views import get_evenimente

app_name = 'adaugasterge'

urlpatterns = [
    path('creare/', views.create_view, name='adauga'),
    path('delete/<int:pk>', views.delete_view, name='sterge'),
    path('get_evenimente/', get_evenimente, name='sda'),
]

semestrul4/pweb/simulari/genericproject/genericproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from genericproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('produse.urls')),
    path('', include('myauth.urls')),
    path('', include('adaugasterge.urls')),
    path('', include('testapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semestrul4/pweb/simulari/genericproject/intrebari/urls.py
from django.urls import path

from intrebari import views

app_name = 'intrebari'

urlpatterns = [
    path('', views.index, name='testapp'),
    path('get_raspunsuri/', views.get_raspunsuri, name='get_raspunsuri'),
    path('sub_raspuns/', views.sub_raspuns, name='sub_raspuns'),
    # path('get_val/', views.get_val, name='get_val'),
    # path('get_fames/', views.get_fames, name='fames'),
    # path('flush/', views.my_flush)
]

semestrul4/pweb/simulari/genericproject/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth import views

app_name = 'myauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('change_password/', views.change_password, name='change_password'),
    path('upload_avatar/', views.upload_avatar, name='add_avatar'),
    path('register/', views.register, name="register"),
    path('logout', views.logout_view, name='logout'),
]

semestrul4/pweb/simulari/genericproject/intrebari/models.py
from django.db import models


# Create your models here.
from myauth.models import MyUser


class Intrebare(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)


class Raspuns(models.Model):
    intrebare = models.ForeignKey(Intrebare, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    text = models.TextField()

semestrul4/pweb/simulari/genericproject/intrebari/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.serializers import serialize

# Create your views here.
from intrebari.models import Intrebare, Raspuns
from myauth.models import MyUser


def index(request):
    intrebari = Intrebare.objects.order_by('-data')
    return render(request, 'intrebari/testapp.html', {'intrebari': intrebari})


def get_raspunsuri(request):
    id = int(request.GET.get('id_intrebare')[2:])
    intrebare = get_object_or_404(Intrebare, pk=id)
    raspunsuri = Raspuns.objects.filter(intrebare=intrebare).order_by('-data')
    real_json = json.loads(serialize('json', raspunsuri))

    my_json = {'raspunsuri': [model['fields'] for model in real_json]}
    for i, el in enumerate(my_json['raspunsuri']):
        user = MyUser.objects.get(id=el['user'])
        el['nume'] = user.username
        if user.avatar:
            el['avatar'] = user.avatar.url
        else:
            el['avatar'] = '/files/imagini/anonim.png'
    my_json['authenticated'] = request.user.is_authenticated
    return HttpResponse(json.dumps(my_json), content_type='application/json')


@login_required
def sub_raspuns(request):
    raspuns = request.GET.get('raspuns')
    id_intrebare = int(request.GET.get('id_intrebare')[2:])
    if raspuns:
        Raspuns.objects.create(intrebare=Intrebare.objects.get(pk=id_intrebare), user=request.user, text=raspuns)
    return HttpResponse(json.dumps({}), content_type='application/json')

semestrul4/pweb/simulari/genericproject/intrebari/templates/intrebari/index.html
{% extends "myauth/base.html" %}

{% block title %}
Index
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'myauth:change_password' %}">Schimba parola</a>
        <a href="{% url 'myauth:add_avatar' %}">Schimba avatar</a>
        <a href="{% url 'adaugasterge:adauga' %}">Adauga intrebare</a>
    {% endif %}

    {% if intrebari %}
        <div id="intrebari">
            {% for intrebare in intrebari %}
                <div class="intrebare">
                    <p id="id{{ intrebare.pk }}">{{ intrebare.text }} {{ intrebare.data }}


                        <p class="img-container">
                        <img src="{{ intrebare.user.avatar.url }}" />
                        <p class="text-container">{{ intrebare.user.username }} </p>
                        </p>


                    </p>
                </div>
            {% endfor %}
        </div>
    {% else %}
         <p> Nu sunt intrebari</p>
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        $(function () {
            var user_name = "{{ user.username }}";
            var user_image;
            {% if  user.avatar %}
                user_image = "{{ user.avatar.url }}";
            {% else %}
                user_image = "/files/imagini/anonim.png";
            {% endif %}
            var active = '';

            $('.intrebare').on('click', function () {
                if (active !== $(this)){
                    if(active !== ''){
                        active.children('div').empty();
                        $('input').remove();
                    }

                    active = $(this);
                    let this_object = $(this);
                    let nr_intrebare = $(this).children('p').attr('id');

                    makeXHR('/get_raspunsuri', 'GET', {'id_intrebare': nr_intrebare})
                        .done(function (data) {
                            let raspunsuri = this_object.children('div');
                            if (data['raspunsuri'].length !== 0){
                                for(let el of data['raspunsuri']){
                                    adaguaRaspuns(el, this_object);
                                }
                            } else {
                                this_object.append($('<div>').text('Nu sunt raspunsuri'))
                            }
                            if (data['authenticated']){
                                let input_raspuns = $('<input>').keypress(function (e) {
                                    if (e.which == 13){
                                        let message = $(this).val();
                                        makeXHR('/sub_raspuns', 'GET', {'raspuns': message, 'id_intrebare': nr_intrebare})
                                            .done(function (data) {
                                                adaguaRaspuns({'nume': user_name, 'avatar': user_image, 'text': message, 'data': ' '}, this_object)
                                            })

                                    }
                                });
                                input_raspuns.insertAfter(this_object);
                            }
                        })
                }
            });
            function adaguaRaspuns(el, this_object){
                let div_text = $('<div>').addClass('text-container').text(el['nume']);
                let div_img = $('<div>').addClass('img-container').append($('<img>').attr('src', el['avatar']))
                    .append(div_text);

                let el_raspuns = $('<div>').append($('<span>').text(el['text'] + ' ' + el['data']))
                    .append(div_img);
                this_object.append(el_raspuns);
            }
        })
    </script>
{% endblock %}