semestrul4/pweb/simulari/genericproject/adaugasterge/urls.py
from django.urls import path

from adaugasterge import views
from testapp.views import get_evenimente

app_name = 'adaugasterge'

urlpatterns = [
    path('creare/', views.create_view, name='adauga'),
    path('delete/<int:pk>', views.delete_view, name='sterge'),
    path('get_evenimente/', get_evenimente, name='sda'),
]

semestrul4/pweb/simulari/genericproject/genericproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from genericproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('produse.urls')),
    path('', include('myauth.urls')),
    path('', include('adaugasterge.urls')),
    path('', include('testapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semestrul4/pweb/simulari/genericproject/hangman/urls.py
from django.urls import path

from hangman import views

app_name = 'hangman'

urlpatterns = [
    path('', views.index, name='testapp'),
    path('get_val/', views.get_val, name='get_val'),
    path('get_fames/', views.get_fames, name='fames'),
    path('flush/', views.my_flush)
]

semestrul4/pweb/simulari/genericproject/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth import views

app_name = 'myauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('change_password/', views.change_password, name='change_password'),
    path('upload_avatar/', views.upload_avatar, name='add_avatar'),
    path('register/', views.register, name="register"),
    path('logout', views.logout_view, name='logout'),
]

semestrul4/pweb/simulari/genericproject/hangman/models.py
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models


class Cuvant(models.Model):
    content = models.CharField(max_length=6, validators=[MinLengthValidator(4), MaxLengthValidator(6)])

    def __str__(self):
        return self.content


class HallOfTime(models.Model):
    nume = models.CharField(max_length=100)
    criteriu = models.FloatField()


class HallOfMistakes(models.Model):
    nume = models.CharField(max_length=100)
    criteriu = models.IntegerField()

semestrul4/pweb/simulari/genericproject/hangman/forms.py
from django import forms

from hangman.models import Cuvant


class CuvantForm(forms.ModelForm):
    class Meta:
        model = Cuvant
        fields = ['content']

semestrul4/pweb/simulari/genericproject/hangman/views.py
import datetime
import json
import random

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core import serializers
from hangman.models import Cuvant, HallOfTime, HallOfMistakes


def index(request):
    all_cuvinte = Cuvant.objects.all()
    cuvant = None
    greseli = None
    if 'greseli' in request.session:
        greseli = request.session['greseli']
    if request.user.is_authenticated:
        pass
    else:
        if 'level' in request.session:
            level = request.session['level']
        else:
            level = 4
            request.session['level'] = level
            request.session['greseli'] = 0
            greseli = 0
            request.session['first_call'] = True
            request.session['time'] = str(datetime.datetime.now())

        if request.session.get('first_call'):
            request.session['first_call'] = False
            cuvinte_level = [cuvant for cuvant in all_cuvinte if len(cuvant.content) == level]
            if not cuvinte_level:
                return HttpResponse('Nu sunt cuvinte in baza de date pentru acest nivel')
            if len(cuvinte_level) > 1:
                cuvant = cuvinte_level[random.randrange(0, len(cuvinte_level) - 1)]
            else:
                cuvant = cuvinte_level[0]
            request.session['cuvant_id'] = cuvant.pk
            cuvant = getHiddenWord(cuvant.content)
            request.session['cuvant'] = cuvant
        else:
            cuvant = request.session['cuvant']

    return render(request, 'hangman/main.html', {'cuvant': cuvant, 'all_cuvinte': all_cuvinte, 'greseli': greseli})


def getHiddenWord(cuvant):
    inceput_final = (cuvant[0], cuvant[-1])
    rez = ''
    for char in cuvant:
        if char in inceput_final:
            rez += char
        else:
            rez += '*'
    return rez


def get_val(request):
    litera = request.GET.get('litera')
    cuvant = Cuvant.objects.get(pk=request.session['cuvant_id']).content
    greseli = True
    rez = ''
    for char1, char2 in zip(request.session['cuvant'], cuvant):
        if char1 == char2:
            rez += char2
        elif char2 == litera:
            rez += char2
            greseli = False
        else:
            rez += '*'
    request.session['cuvant'] = rez
    if greseli:
        greseli = request.session['greseli'] + 1
        request.session['greseli'] = greseli

    win = False
    restart = False
    in_time_hall = False
    in_greseli_hall = False
    if '*' not in rez:
        request.session['level'] += 1
        request.session['first_call'] = True
        restart = True

    if request.session['level'] == 7:
        win = True
        restart = False
        current_time = datetime.datetime.now()
        begin = datetime.datetime.strptime(request.session['time'], "%Y-%m-%d %H:%M:%S.%f")
        delta = (current_time - begin).total_seconds()
        request.session['delta'] = delta
        in_time_hall = verify_hall(HallOfTime, 'time_hall', delta, request.session)
        in_greseli_hall = verify_hall(HallOfMistakes, 'greseli_hall', request.session['greseli'], request.session)
        if not in_time_hall and not in_greseli_hall:
            request.session.flush()

    return HttpResponse(json.dumps({'cuvant': rez,
                                    'greseli': greseli,
                                    'restart': restart,
                                    'win': win,
                                    'in_hall': in_time_hall or in_greseli_hall,
                                    }), content_type='application/json')


def get_fames(request):
    time_hall = request.session.get('time_hall')
    greseli_hall = request.session.get('greseli_hall')
    if time_hall:
        HallOfTime.objects.create(nume=request.GET.get('name', 'Anonim'), criteriu=request.session['delta'])
    if greseli_hall:
        HallOfMistakes.objects.create(nume=request.GET.get('name', 'Anonim'), criteriu=request.session['greseli'])
    time = serializers.serialize('json', HallOfTime.objects.order_by('criteriu')[:3])
    greseli = serializers.serialize('json', HallOfMistakes.objects.order_by('criteriu')[:3])
    data = {'Hall_time': [el['fields'] for el in json.loads(time)],
            'Hall_mistakes': [el['fields'] for el in json.loads(greseli)],
            }
    request.session.flush()
    return HttpResponse(json.dumps(data), content_type='application/json')


def verify_hall(hall, hall_name, number,  session):
    in_hall = False
    time_hall = hall.objects.all().order_by('criteriu')[:3]
    if len(time_hall) < 3:
        in_hall = True
        session[hall_name] = True
    for i, hall in enumerate(time_hall):
        if number < hall.criteriu:
            in_hall = True
            session[hall_name] = True
    return in_hall


def my_flush(request):
    request.session.flush()
    return HttpResponse('flushed')

semestrul4/pweb/simulari/genericproject/hangman/templates/hangman/main.html
{% extends 'myauth/base.html' %}
{% block title %}
Main
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'adaugasterge:adauga' %}">Adauga</a>
        {% for cuvantt in all_cuvinte %}
            <h5>{{ cuvantt }} <a href="{% url 'adaugasterge:sterge' cuvantt.id %}">Sterge Cuvant</a> </h5>
        {% endfor %}
    {% else %}
        Greseli: <span id="greseli">{{ greseli }}</span>
        <div id="cuvant">{{ cuvant }}</div>

        <input id="input-area" type="text">
        <div id="basicUsage">0</div>

        <div id="castigat"></div>

    {% endif %}
{% endblock %}

{% block js %}

    <script>
        $(function () {
            var litera = $('#input-area');
            var cuvant = $('#cuvant');
            var greseli = $("#greseli");
            var win = $("#castigat");
            var clock = $('#basicUsage')

            setInterval(function() {
                clock.text(parseInt(clock.text()) + 1);
            }, 1000);

            litera.on('input', function () {
                makeXHR('/get_val', 'get', {'litera': $(this).val()})
                    .done(function (data) {
                        if(data['win']){
                            win.text('Ai castigat');
                            if(data['in_hall']){
                                win.append($('<p>').text('Introdu numele')).append($('<input>').keypress(function (e) {
                                    if(e.which == 13) {
                                        get_fames({'name': $(this).val()});
                                        $(this).hide();
                                    }
                                }));
                            } else {
                                get_fames({});
                            }
                        }
                        if(data['restart'])
                            location.reload();
                        if(! data['greseli']){
                            cuvant.text(data['cuvant']);
                        } else {
                            greseli.text(parseInt(greseli.text()) + 1);
                        }
                        litera.val('');
                    })
            });

            function get_fames(data_param) {
                makeXHR('/get_fames', 'GET', data_param)
                    .done(function (data) {
                        let tbody1 = $('<tbody>');
                        let table1 = $('<table>').attr('id', 'table1').append(tbody1);

                        win.append($('<h1>').text('Hall of time')).append(table1);
                        tbody1.append($('<tr>').append($('<th>').text('nume')).append($('<th>').text('secunde')));

                        for(let element of data['Hall_time']){
                            tbody1.append($('<tr>').append($('<td>').text(element['nume'])).append($('<td>').text(element['criteriu'])))
                        }
                        table1.addClass('sortable');

                        let tbody2 = $('<tbody>');
                        let table2 = $('<table>').attr('id', 'table2').append(tbody2);
                        win.append($('<h1>').text('Hall of mistakes')).append(table2);
                        tbody2.append($('<tr>').append($('<th>').text('nume')).append($('<th>').text('greseli')));

                        for(let element of data['Hall_mistakes']){
                            tbody2.append($('<tr>').append($('<td>').text(element['nume'])).append($('<td>').text(element['criteriu'])))
                        }

                        table2.addClass('sortable');
                        sorttable.makeSortable(document.getElementById('table1') );
                        sorttable.makeSortable(document.getElementById('table2') );
                    })
            }
        })
    </script>
{% endblock %}