semestrul4/mpp/simulari/genericproject/genericproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ski2.urls')),
    # path('', include('myauth.urls')),
]

semestrul4/mpp/simulari/genericproject/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth import views

app_name = 'myauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name="register"),
    path('logout', views.logout_view, name='logout'),
]

semestrul4/mpp/simulari/genericproject/ski2/urls.py
from django.urls import path

from ski2 import views

app_name = 'ski2'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('participanti/', views.get_participanti, name='get_participanti')
    # path('<int:pk>/voteaza/', views.update_participant, name='voteaza')
    path('probe', views.get_probe, name='probe'),
    path('proba/creare_probe', views.creare_probe, name="creare_probe"),
    path('login', views.login_view, name='login'),
    path('', views.create_account, name='create_acc'),
]

semestrul4/mpp/simulari/genericproject/myauth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class MyUser(AbstractUser):
    def __str__(self):
        return f'{self.username} {self.email}'

    ASPECT_CHOICES = (
        ('lungime', 'lungime'),
        ('stil', 'stil'),
        ('aterizare', 'aterizare')
    )

    aspect = models.CharField(max_length=40, choices=ASPECT_CHOICES, default='lungime')

semestrul4/mpp/simulari/genericproject/myauth/forms.py
from django import forms

from myauth.models import MyUser


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'password']
        help_texts = {
            'username': None,
        }

        widgets = {'password': forms.PasswordInput,
                   'username': forms.TextInput(attrs={'autofocus': True}),
                  }

semestrul4/mpp/simulari/genericproject/myauth/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect

from genericproject import settings
from myauth.forms import UserRegistrationForm


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user)
            return redirect(f'{settings.current_app}:index')
    else:
        form = UserRegistrationForm()
    return render(request, 'myauth/register.html', {'form': form})


def login_view(request):
    error = None
    if request.POST:
        form = UserRegistrationForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(f'{settings.current_app}:index')
        error = 'Autentificare esuata'
    else:
        form = UserRegistrationForm()
    return render(request, 'myauth/login.html', {'error': error, 'form': form})


def logout_view(request):
    logout(request)
    # INSERT APP NAME HERE
    return redirect(f'{settings.current_app}:index')


def test_view(request):
    pass

semestrul4/mpp/simulari/genericproject/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% if user.is_authenticated %}
        <div>
            <h1>{{ user }} {{ user.id }}</h1>
            <a href="{% url 'myauth:logout' %}">Logout</a>
        </div>
        <br><br>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
{% load static %}
<script type="text/javascript" src={% static "myauth/jquery.js/"%}>
    {#debug.log($("#1"));#}
</script>
{% block js  %}
{% endblock %}
</html>

semestrul4/mpp/simulari/genericproject/myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}

{% block title %}
Autentificare
{% endblock %}

{% block content %}
{% if error %}
    {{ error }}
{% endif %}
<form method="post" action="{% url 'myauth:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<a href="{% url 'myauth:register'%}">Create a new account</a>

{% endblock %}

semestrul4/mpp/simulari/genericproject/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
Register
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Register</button>
</form>
{% endblock %}