semestrul4/pweb/simulari/genericproject/genericproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from genericproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('produse.urls')),
    path('', include('myauth.urls')),
    path('', include('adaugasterge.urls')),
    path('', include('testapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

semestrul4/pweb/simulari/genericproject/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth import views

app_name = 'myauth'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('change_password/', views.change_password, name='change_password'),
    path('upload_avatar/', views.upload_avatar, name='add_avatar'),
    path('register/', views.register, name="register"),
    path('logout', views.logout_view, name='logout'),
]

semestrul4/pweb/simulari/genericproject/produse/urls.py
from django.urls import path

from produse import views

app_name = 'produse'

urlpatterns = [
    path('', views.index, name='testapp'),
    path('creare_produs/', views.create_view, name='creare_produs'),
    path('delete_produs/<int:pk>', views.delete_view, name='delete_produs'),
    path('filter/', views.filter, name='filter'),
    path('get_detail/', views.get_detail, name='detail'),
]

semestrul4/pweb/simulari/genericproject/produse/models.py
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class Produse(models.Model):
    nume = models.CharField(max_length=100)
    descriere = models.CharField(max_length=100)
    producator = models.CharField(max_length=100)
    pret = models.IntegerField(validators=[MinValueValidator(0)])
    cantitate = models.IntegerField(validators=[MinValueValidator(0)])
    poza = models.ImageField(upload_to='imagini/')


class Popularitate(models.Model):
    produs = models.ForeignKey(Produse, on_delete=models.CASCADE)
    creare = models.TimeField(auto_now_add=True)

semestrul4/pweb/simulari/genericproject/produse/forms.py
from django import forms

from produse.models import Produse


class ProdusForm(forms.ModelForm):
    class Meta:
        model = Produse
        fields = ['nume', 'descriere', 'producator', 'pret', 'cantitate', 'poza']

        widgets = {
        #     'password': forms.PasswordInput,
        #     'username': forms.TextInput(attrs={'autofocus': True}),
        }

semestrul4/pweb/simulari/genericproject/produse/views.py
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from produse.forms import ProdusForm
from produse.models import Produse, Popularitate


def index(request):
    produse = None
    if request.user.is_authenticated:
        produse = Produse.objects.all()
    return render(request, 'produse/testapp.html', {'produse': produse})


@login_required
def create_view(request):
    if request.method == 'POST':
        form = ProdusForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            Popularitate.objects.create(produs=form.instance)
            return redirect('produse:testapp')
    else:
        form = ProdusForm()
    return render(request, 'adaugasterge/creare.html', {'form': form})


@login_required
def delete_view(request, pk):
    err = None
    if request.method == 'POST':
        if request.POST.get('raspuns') == 'da':
            Produse.objects.get(pk=pk).delete()
            return redirect('produse:testapp')
        elif request.POST.get('raspuns') == 'nu':
            return redirect('produse:testapp')
        err = 'Trebuie sa alegi o optiune'
    return render(request, 'produse/delete.html', {'err': err})


def filter(request):
    filtru = request.GET['filtru']
    produse = (Produse.objects.values_list('nume', 'poza', 'pk').filter(nume__contains=filtru) |
               Produse.objects.values_list('nume', 'poza', 'pk').filter(descriere__contains=filtru)).distinct()

    produse = [{'nume': values[0], 'poza': values[1], 'pk': values[2]} for values in produse]
    return HttpResponse(json.dumps(produse), content_type='application/json')


def get_detail(request):
    id = int(request.GET.get('id')[2:])
    produs = Produse.objects.get(pk=id)
    Popularitate.objects.create(produs=produs)
    produs.save()
    popularitate = Popularitate.objects.filter(produs=produs).order_by('creare')
    data = {'produs': json.loads(serialize('json', [produs]))[0],
            'popularitate': [{'creare': model['fields']['creare']} for model in json.loads(serialize('json', popularitate))]
            }
    return HttpResponse(json.dumps(data),
                        content_type='application/json')

semestrul4/pweb/simulari/genericproject/produse/templates/produse/index.html
{% extends 'myauth/base.html' %}
{% block title %}
    Index
{% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}
        <a href="{% url 'produse:creare_produs' %}">Adauga Produs</a>
    {% else %}
        <label for="filter-area">Filter</label> <input id="filter-area" type="text">
    {% endif %}
    <ul id="mylist">
        {% if produse %}
            {% for produs in produse %}
            <li>
                Nume: {{ produs.nume }}
                Descriere: {{ produs.descriere }}
                Producator: {{ produs.producator }}
                Pret: {{ produs.pret }}
                Cantitate: {{ produs.cantitate }}
                <img src="{{ produs.poza.url }}" class="myimage">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'produse:delete_produs' produs.pk %}">Sterge produs </a>
                {% endif %}
            </li>
            {% endfor %}
        {% endif %}
    </ul>
    <div id="myModal">
          <div class="modal-content">
            <span class="close">&times;</span>
            <div id="modal-text">
            </div>
          </div>
    </div>
{% endblock %}

{% block js %}
    <script>
      $(function () {
          var modal = $('#myModal');
          var modal_content = $('#modal-text');
          var closeBtn = $('.close');
          var area = $('ul');
          var last_xhr = "";

          $('#filter-area').on('input', function () {
              if(last_xhr.hasOwnProperty('abort'))
                last_xhr.abort();
              last_xhr = makeXHR('/filter', 'GET', {'filtru': $(this).val()})
                  .done(function (data) {
                      area.empty();
                      for(let element of data){
                          let nume = element['nume'];
                          let poza =element['poza'];

                          let el = $('<li>').text(
                              'Nume ' + nume
                          ).append($('<img>').attr('src', 'files'+'/'+poza).addClass('myimage'));

                          area.append(el);
                          el.attr('id', 'id' + element['pk']);
                          put_signal_on(el);
                      }
                  }).fail(function (err) {
                      console.log(err);
                  });
          });

          closeBtn.on('click', function () {
             modal.hide();
          });

          function put_signal_on(element) {
             element.on('click', function () {
                 makeXHR('/get_detail', 'GET', {'id': $(this).attr('id')})
                     .done(function (data) {
                         let model = data['produs'].fields;
                         modal_content.empty();
                         modal.show();
                         modal_content.append($('<img>').attr('src', 'files/' + model['poza']).addClass('modalImage'))
                             .append($('<p>').text('Nume: ' + model['nume']))
                             .append($('<p>').text('descriere: ' + model['descriere']))
                             .append($('<p>').text('producator: ' + model['producator']))
                             .append($('<p>').text('pret: ' + model['pret']))
                             .append($('<div>').attr('id', 'plot'));
                         let datetimes= [];
                         let popularity = [];
                         for (let i=0; i<data["popularitate"].length; i++){
                             datetimes.push(data['popularitate'][i]["creare"]);
                             popularity.push(i);
                         }
                         console.log(datetimes);
                         console.log(popularity);
                         let plot = [
                            {
                                x: datetimes,
                                y: popularity,
                                type: 'scatter'
                            }
                         ];

                        Plotly.newPlot('plot', plot);
                     })
             });
          }

      });
    </script>

{% endblock %}

semestrul4/pweb/simulari/genericproject/produse/templates/produse/produs_delete.html
{% extends 'myauth/base.html' %}
{% block title %}
    Delete
{% endblock %}

{% block content %}
    <p>Sunteti sigur ca doriti sa stergeti produsul?</p>
    {% if err %}
        {{ err }}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label>Da</label><input type="radio" name="raspuns" value="da">
        <label>Nu</label><input type="radio" name="raspuns" value="nu">
        <button type="submit">Rapunde</button>
    </form>
{% endblock %}

semestrul4/pweb/simulari/genericproject/produse/templates/produse/produse_create.html
{% extends 'myauth/base.html' %}
{% block title %}
    Creare produs
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Creeaza</button>
    </form>
{% endblock %}